routingRules:
  - domain: "${RETAIL_DOMAIN}"
    version: "${RETAIL_DOMAIN_VERSION}"
    targetType: "url"
    target:
      url: "http://onix-adapter:8081/bpp/receiver"
    endpoints:
      - discover
      - search
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support
