routingRules:
  - domain: "*"
    version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-2.0:3000/api/webhook"
    endpoints:
      - search
      - discover
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support