routingRules:
  - domain: "${RETAIL_DOMAIN}"
    version: "${RETAIL_DOMAIN_VERSION}"
    targetType: "url"
    target:
      url: "http://onix-adapter:8081/bap/receiver"
    endpoints:
      - on_search
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_track
      - on_cancel
      - on_update
      - on_rating
      - on_support
      - on_discover
